# Generated by Django 6.0.5 on 2026-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_empresa_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='empresa_rel',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
