# Generated by Django 6.0.5 on 2026-06-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_miembroempresa_es_responsable_chat_alter_empresa_id_and_more'),
        ('products', '0004_alter_historialprecio_id_alter_producto_id_and_more'),
        ('users', '0003_remove_user_empresa_rel_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='productos_guardados',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_guardaron', to='products.producto'),
        ),
        migrations.AddField(
            model_name='user',
            name='proveedores_favoritos',
            field=models.ManyToManyField(blank=True, related_name='empresas_seguidoras', to='enterprises.empresa'),
        ),
    ]
