# Generated by Django 6.0.5 on 2026-06-09 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresasFavoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('area_produccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa_favorita', models.ManyToManyField(related_name='empresas_favoritas_rel', through='enterprises.EmpresasFavoritas', to='enterprises.enterprise')),
            ],
        ),
        migrations.AddField(
            model_name='empresasfavoritas',
            name='empresa_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_fav', to='enterprises.enterprise'),
        ),
        migrations.AddField(
            model_name='empresasfavoritas',
            name='empresa_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_favorita_rel', to='enterprises.enterprise'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_autor', to='enterprises.enterprise')),
                ('empresa_evaluada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to='enterprises.enterprise')),
            ],
        ),
    ]
