# Generated by Django 5.2.3 on 2026-06-10 03:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('area_produccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='ValoracionEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Valoraciones',
            },
        ),
        migrations.CreateModel(
            name='EmpresaFavorita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('empresa_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_fav', to='enterprises.empresa')),
                ('empresa_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_favorita_rel', to='enterprises.empresa')),
            ],
            options={
                'verbose_name_plural': 'Empresas Favoritas',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_favorita',
            field=models.ManyToManyField(related_name='empresas_favoritas_rel', through='enterprises.EmpresaFavorita', to='enterprises.empresa'),
        ),
        migrations.CreateModel(
            name='MiembroEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Lector')], default='editor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_empresa', to='enterprises.empresa')),
            ],
            options={
                'verbose_name': 'Miembro de empresa',
                'verbose_name_plural': 'Miembros de empresa',
            },
        ),
    ]
