# Generated by Django 6.0.5 on 2026-06-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresasfavoritas',
            options={'verbose_name_plural': 'Empresas Favoritas'},
        ),
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='valoracion',
            options={'verbose_name_plural': 'Valoraciones'},
        ),
    ]
