# Generated by Django 5.2.3 on 2026-06-10 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroempresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_miembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valoracionempresa',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_autor', to='enterprises.empresa'),
        ),
        migrations.AddField(
            model_name='valoracionempresa',
            name='empresa_evaluada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to='enterprises.empresa'),
        ),
        migrations.AddConstraint(
            model_name='miembroempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario'), name='unique_empresa_user_membership'),
        ),
    ]
