# Generated by Django 6.0.5 on 2026-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_miembroempresa_es_responsable_chat_alter_empresa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/'),
        ),
    ]
