# Generated by Django 6.0.5 on 2026-06-09 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion_producto', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_minima_pedido', models.IntegerField()),
                ('categoria', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('stock_disponible', models.IntegerField()),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='enterprises.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_antiguo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('producto_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_producto_autor', to='enterprises.enterprise')),
                ('producto_evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to='products.producto')),
            ],
        ),
    ]
