# Generated by Django 5.2.3 on 2026-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.AddField(
            model_name='valoracionproducto',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('tecnologia', 'Tecnología y Software'), ('maquinaria', 'Maquinaria y Equipos'), ('insumos', 'Insumos y Materias Primas'), ('servicios', 'Servicios Profesionales'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
