# Generated by Django 6.0.5 on 2026-06-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialprecio',
            options={'verbose_name_plural': 'Historiales de Precios'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='valoracionproducto',
            options={'verbose_name_plural': 'Valoraciones de Productos'},
        ),
    ]
