# Generated by Django 5.2.3 on 2026-06-10 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_novedad', models.CharField(max_length=255)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='enterprises.empresa')),
                ('producto_referido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_referidas', to='products.producto')),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_autor', to='enterprises.empresa')),
                ('producto_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_producto', to='products.producto')),
                ('publicacion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_publicacion', to='publications.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
