# Generated by Django 6.0.5 on 2026-06-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
    ]
