# Generated by Django 6.0.5 on 2026-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='autor_id',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='publicacion_id',
            new_name='publicacion',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
